version: "3"
services:
  node-app:
    image: ${IMAGE_NAME}
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start
