version: "3"
services:
  node-app:
    image: gcr.io/$${{ secrets.GCP_PROJECT_ID }}/$${{ secrets.GCP_APP_NAME }}
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start
